name: gradient_ui_plus
description: UI widgets with gradient support. Supports many widgets like Elevated/TextButton, FloatingActionButton, Icon, IconButton, Text, SelectableText etc with more to come.
version: 1.0.1
homepage: https://github.com/deepak07082/gradient_ui_plus.git
repository: https://github.com/deepak07082/gradient_ui_plus.git
issue_tracker: https://github.com/deepak07082/gradient_ui_plus/issues

topics:
  - gradient
  - gradient_ui


environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
